version : "3"

services:     

    db:
        container_name: container-db 
        image: mysql:latest
        ports:
            - 3306:3306 
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sabiinsearch
            - MYSQL_PASSWORD=login_123
            - MYSQL_DATABASE=mySQL_DB 

    rest:
        image:
        ports:
            -8080:8080
        depends_on:
            - db