version : "3"

services:     
           
    spring-service:

      container_name: spring-service
      image: springboot-mysql:1.0
      ports:
       - "5001:8080"
      depends_on:
       - mysql-service
        
    mysql-service:

      container_name: mysql-service 
      image: mysql:5.7
      ports:
       - "3306:3306" 
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=sabiinsearch
       - MYSQL_PASSWORD=login_123
       - MYSQL_DATABASE=mySQL_DB 
     